n=(input("Enter Your Name \n"))
print (n)
p= int (input("Enter Amount Given as Principal\n "))
print (p)
r=float (input ("Enter Rate of Interest (Without %)\n"))
print (r)
t=float(input ("Enter Number Of Years\n"))
print (t)
print ("Recheck the value entered",n," \n Principal",p," \n Rate of Interest",r,"\n Time in Years",t)
i= ((p*r*t)/100)
print ("Simple Interest accumulated is ",i)
a= (p+i)
print("Total amount to be paid by ",n ,"is" , a)
